---
title: "Replication of Study Expecting the unexpected by Jiang & Filik (2025, Memory & Cognition)"
author: "Lumi Kang"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction
[Justification]
My current research investigates how comprehenders use grammatical cues and world-knowledge to construct mental representations of counterfactual sentences. Jiang and Filik (2025) address a related question: how does world-knowledge interact with relatively less constraining contexts, such as dreams, that allow implausible events without explicitly predicting them? I am particularly interested in replicating Experiment 2, which used self-paced reading to examine how this interaction unfolds during comprehension. This experiment is relevant to my research because it investigates how readers accommodate information that conflicts with real-world knowledge when the context permits an alternative reality. Conducting this replication would also give me experience using behavioral reading-time measure to investigate questions related to my current EEG research.

[Implementation and Challenges]
The original experiment was conducted online using PCIbex and the authors shared the stimulus lists and analysis scripts. However, I have not located the original experiment code and used PICbex before. I therefore plan to implement the task in jsPsych while preserving the original stimuli, word-by-word presentation, response procedure, counterbalancing, and trial-order constraints as closely as possible. Recreating the task in Javascript will be a methodological challenge, as my programming experience is primarily in Python, but it will also provide an opportunity to develop skills for future online experiments. Additional challenges include verifying the accuracy of recorded reading times and recruiting a sufficient sample of eligible participants through SONA.



## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
